### ISSUE TITLE
error: undefined reference to `EVP_CIPHER_CTX_new'

### ISSUE THREAD

**Issue by tonyLMs** [s12mmm3/QCloudMusicApi#17]
crypto.h 中出现该问题，好像是evp.h的库连接出现问题？求解答

**Comment by s12mmm3** [comment]
EVP_CIPHER_CTX_new是openssl里的东西，估计是本地没找到openssl的头文件和库

**Comment by s12mmm3** [comment]
或者你试一下openssl-cmake这个分支

**Comment by s12mmm3** [comment]
openssl已使用CMake构建
