### ISSUE TITLE
Ubuntu 20.04编译出错

### ISSUE THREAD

**Issue by Greedysky** [s12mmm3/QCloudMusicApi#27]
按照[手动编译](https://github.com/s12mmm3/QCloudMusicApi?tab=readme-ov-file#%E6%89%8B%E5%8A%A8%E7%BC%96%E8%AF%91)，出现如下错误：

![captrue](https://github.com/s12mmm3/QCloudMusicApi/assets/7044256/630c52f1-4c4c-4972-9822-20df47311c43)
看错误应该是找不到对应的库，请问如何解决。

**Comment by Greedysky** [comment]
另外是否有Linux版本的可执行程序？

**Comment by s12mmm3** [comment]
更新一下子模块吧，子模块没拉取
git submodule update --init --recursive

**Comment by s12mmm3** [comment]
😂linux没必要传可执行程序吧，编一下就好

**Comment by Greedysky** [comment]
> 更新一下子模块吧，子模块没拉取 git submodule update --init --recursive

可以了。另外可以把子模块的更新也加到手动编译教程中。
