### ISSUE TITLE
Linux下直接调用c_api会crash

### ISSUE THREAD

**Issue by zeyugao** [s12mmm3/QCloudMusicApi#29]
把 `example/capi.py` 下面的 `QCloudMusicApi.dll` 改成 `libQCloudMusicApi.so`，python就会直接crash

<img width="1219" alt="image" src="https://github.com/s12mmm3/QCloudMusicApi/assets/6374697/6b941a96-fc12-4640-b21d-d01ae3a84ae2">

用一个这样的代码，在 `build/bin` 文件夹下面进行编译

```
#include "../../QCloudMusicApi/api_c.h"

int main()
{
    invoke("login_qr_key", "{}");
}
```

```
gcc main.c ./libQCloudMusicApi.so -o main
LD_LIBRARY_PATH=. ./main
```

<img width="1244" alt="image" src="https://github.com/s12mmm3/QCloudMusicApi/assets/6374697/05f90ccd-4099-4245-a610-4c335a708f7b">

gdb调试看是挂在了

<img width="1221" alt="image" src="https://github.com/s12mmm3/QCloudMusicApi/assets/6374697/b5d32eaa-b3e9-41fd-9049-3496517edae4">

系统是 ubuntu 22.04，qt版本6.2.4

**Comment by s12mmm3** [comment]
python调用还有点问题，Qt的网络库找不到openssl，我看一下

**Comment by s12mmm3** [comment]
拉下最新代码试试python调用

**Comment by zeyugao** [comment]
是可以调用了，谢谢
