### ISSUE TITLE
cookie、login_status返回不完整

### ISSUE THREAD

**Issue by zeyugao** [s12mmm3/QCloudMusicApi#30]
在用 `login_qr_check` 接口得到结果之后，虽然网易返回的cookie有很多，但是好像返回到json里面的只有第一个

<img width="1099" alt="image" src="https://github.com/s12mmm3/QCloudMusicApi/assets/6374697/05ed5df2-61f5-418c-8fcb-209b4c494f62">

`login_status` 好像也不知道为什么没有把body传回到api前面

<img width="1188" alt="image" src="https://github.com/s12mmm3/QCloudMusicApi/assets/6374697/40642454-0846-4d93-8bd7-99e326b91ea0">

都是用的capi，翻了一下代码，没看懂哪里错了（

**Comment by s12mmm3** [comment]
试一下最新代码

**Comment by zeyugao** [comment]
cookie返回的完整了

**Comment by zeyugao** [comment]
<img width="1165" alt="image" src="https://github.com/s12mmm3/QCloudMusicApi/assets/6374697/dca6859b-ed70-48f1-8d80-fa5e59429a8c">

但是把domain相关的去掉之后，cookie里面还留着什么登陆的信息吗

**Comment by s12mmm3** [comment]
额 好像删多了，试试最新代码

**Comment by zeyugao** [comment]
cookie完整了

这里少了一个 QVariantMap


```diff
diff --git a/QCloudMusicApi/module.cpp b/QCloudMusicApi/module.cpp
index a43e0e4..650b181 100644
--- a/QCloudMusicApi/module.cpp
+++ b/QCloudMusicApi/module.cpp
@@ -2360,7 +2360,7 @@ QVariantMap Api::login_status(QVariantMap query) {
         body["cookie"] = result["cookie"];
         result = QVariantMap {
             { "status", 200 },
-            { "body", {
+            { "body", QVariantMap {
                          { "data", result["body"] }
                      } },
             { "cookie", result["cookie"] }
```

**Comment by zeyugao** [comment]
以及问一下既然已经自己build openssl了，为什么不静态链接进去呢

我现在在单独地为openssl `set(BUILD_SHARED_LIBS OFF)` ，结束之后再开回来

**Comment by s12mmm3** [comment]
Qt的网络库会动态链接到OpenSSL；静态链接就找不到了，得手动拷贝一份OpenSSL的动态库

**Comment by s12mmm3** [comment]
静态链接也可以，就是OpenSSL的依赖问题得自己处理一下，不同Qt版本网络库依赖的OpenSSL版本不同
