### ISSUE TITLE
anonymous_token的初始化时机

### ISSUE THREAD

**Issue by zeyugao** [s12mmm3/QCloudMusicApi#42]
anonymous_token现在是用这个初始化方式

https://github.com/s12mmm3/QCloudMusicApi/blob/2924a49c7f78ba388af68280355d015ff325d294/QCloudMusicApi/util/request.cpp#L25-L30

我现在用这个库的时候是动态链接上去的，在调用invoke之前，会设置一下环境变量 `QT_LOGGING_RULES=*.debug=false` 来关掉debug信息，依赖qt在我设置环境变量后初始化

但是anonymous_token在init的时候就调用了，使得我的应用程序没法干预qt的初始化过程，导致QT_LOGGING_RULES的设置无效，可以改改anonymous_token的初始化方式吗，在调用的时候再去使用。

而且现在anonymous_token这个文件依赖于ApiServer生成，如果没有启动过ApiServer，这个文件就永远不存在，使得anonymous_token是空的

**Comment by s12mmm3** [comment]
可以的，我改下anonymous_token的生成时机；
anonymous_token文件不存在没关系，调用一下Api的`register_anonimous`接口就行，一样的效果
