### ISSUE TITLE
scrobble接口是有效的吗

### ISSUE THREAD

**Issue by zeyugao** [s12mmm3/QCloudMusicApi#43]
听歌打卡接口里面，即使返回了200和success，但是在手机上面看听歌时间仍然是没有变的

我看和nodejs那一边做对比，好像也没有区别

**Comment by s12mmm3** [comment]
听说有播放记录，听歌时间就不知道了

**Comment by zeyugao** [comment]
好像这个接口只是一个log，不管传什么东西上去都是200结果

**Comment by zeyugao** [comment]
这个 https://github.com/s12mmm3/QCloudMusicApi/commit/c9b261a8239f321bfc32d9a4015aae78d50edbf6 改了之后可以正常打卡，但是过几天之后打卡记录就没掉了。。

**Comment by s12mmm3** [comment]
应该少传参数了，被当成异常数据清掉了
